version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pokemon_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pokemon123
      POSTGRES_DB: pokemon_etl
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pokemon_app
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pokemon123
      DB_NAME: pokemon_etl
    ports:
      - "8501:8501"

volumes:
  postgres_data: