"""Initial migration: Create tables for Pokemon ETL

Revision ID: 2b1e96a6f91b
Revises: 
Create Date: 2026-03-06 21:20:29.940651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1e96a6f91b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metricas_etl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha_ejecucion', sa.DateTime(), nullable=True),
    sa.Column('registros_extraidos', sa.Integer(), nullable=True),
    sa.Column('registros_guardados', sa.Integer(), nullable=True),
    sa.Column('registros_fallidos', sa.Integer(), nullable=True),
    sa.Column('tiempo_ejecucion_segundos', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('mensaje', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Integer(), nullable=True),
    sa.Column('experiencia_base', sa.Integer(), nullable=True),
    sa.Column('tipos', sa.String(length=100), nullable=True),
    sa.Column('habilidades', sa.Text(), nullable=True),
    sa.Column('habilidades_ocultas', sa.Text(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('ataque', sa.Integer(), nullable=True),
    sa.Column('defensa', sa.Integer(), nullable=True),
    sa.Column('ataque_especial', sa.Integer(), nullable=True),
    sa.Column('defensa_especial', sa.Integer(), nullable=True),
    sa.Column('velocidad', sa.Integer(), nullable=True),
    sa.Column('total_movimientos', sa.Integer(), nullable=True),
    sa.Column('es_legendario', sa.Boolean(), nullable=True),
    sa.Column('es_mitico', sa.Boolean(), nullable=True),
    sa.Column('tasa_captura', sa.Integer(), nullable=True),
    sa.Column('felicidad_base', sa.Integer(), nullable=True),
    sa.Column('habitat', sa.String(length=100), nullable=True),
    sa.Column('generacion', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('sprite_frente', sa.Text(), nullable=True),
    sa.Column('sprite_shiny', sa.Text(), nullable=True),
    sa.Column('fecha_extraccion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nombre', 'pokemon', ['nombre'], unique=False)
    op.create_index('idx_tipos', 'pokemon', ['tipos'], unique=False)
    op.create_index(op.f('ix_pokemon_nombre'), 'pokemon', ['nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemon_nombre'), table_name='pokemon')
    op.drop_index('idx_tipos', table_name='pokemon')
    op.drop_index('idx_nombre', table_name='pokemon')
    op.drop_table('pokemon')
    op.drop_table('metricas_etl')
    # ### end Alembic commands ###
