[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#CC0000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#2c3e50"
font = "sans serif"